export const undoWindowMs = 3000;

export const categoryDefinitions = [
  { name: '全て', active: true },
  { name: '揚げ場', station: '揚げ場', alert: true },
  { name: '鉄板・焼き', station: '鉄板・焼き' },
  { name: '麺・パスタ', fallbackCount: 1 },
  { name: 'サラダ・前菜', station: 'サラダ・前菜' },
  { name: 'デザート', fallbackCount: 1 },
  { name: 'ドリンク', station: 'ドリンク' },
];

export const stationByCategoryId = {
  fried: '揚げ場',
  griddle: '鉄板・焼き',
  salad: 'サラダ・前菜',
  drink: 'ドリンク',
};

export const masonryLayoutByMenuId = {
  karaage: {
    minColumns: 3,
    maxCardsPerColumn: 4,
    maxColumns: 14,
    targetColumnHeight: 470,
  },
  gyoza: {
    minColumns: 3,
    maxCardsPerColumn: 4,
    targetColumnHeight: 470,
  },
  caesar: {
    minColumns: 2,
    maxCardsPerColumn: 4,
    targetColumnHeight: 470,
  },
  highball: {
    minColumns: 2,
    maxCardsPerColumn: 4,
    targetColumnHeight: 470,
  },
};

export const mockOrderItems = [
  ...createOrderItemRows({
    categoryId: 'fried',
    menuId: 'karaage',
    name: '若鶏の唐揚げ',
    rows: [
      {
        id: 'fried-t7',
        tableNo: 'T7',
        elapsed: 18,
        quantity: 2,
        options: [
          '+レモン別添え',
          'ソース別皿',
          'カット小さめ',
          '衣うすめ',
          '先出し希望',
          '紙ナプキン多め',
          '取り皿追加',
          'マヨ別添え',
          '唐辛子なし',
          '塩少なめ',
        ],
        memo:
          '子ども用なので辛味なしで、衣は薄め、塩も控えめ。できれば先に出してください。取り皿と紙ナプキンも一緒にお願いします。アレルギー確認あり。',
      },
      {
        id: 'fried-t24',
        tableNo: 'T24',
        elapsed: 15,
        quantity: 1,
        options: ['塩少なめ'],
        memo: '熱めで',
      },
      {
        id: 'fried-t22',
        tableNo: 'T22',
        elapsed: 14,
        quantity: 3,
        options: [],
        memo: '衣しっかり',
      },
      {
        id: 'fried-t19',
        tableNo: 'T19',
        elapsed: 13,
        quantity: 1,
        options: ['マヨ別添え', '取り皿追加'],
        memo: '先出し',
      },
      {
        id: 'fried-t15',
        tableNo: 'T15',
        elapsed: 12,
        quantity: 2,
        options: ['ソースなし'],
        memo: '一つだけ小さめ',
      },
      {
        id: 'fried-t10',
        tableNo: 'T10',
        elapsed: 11,
        quantity: 1,
        options: ['レモン多め'],
        memo: '揚げたて希望',
      },
      {
        id: 'fried-t41',
        tableNo: 'T41',
        elapsed: 10,
        quantity: 1,
        options: [],
        memo: '揚げ色薄め',
      },
      {
        id: 'fried-t3',
        tableNo: 'T3',
        elapsed: 9,
        quantity: 1,
        options: [],
        memo: '',
      },
      {
        id: 'fried-t38',
        tableNo: 'T38',
        elapsed: 9,
        quantity: 4,
        options: ['紙ナプキン多め'],
        memo: '人数分取り皿',
      },
      {
        id: 'fried-t36',
        tableNo: 'T36',
        elapsed: 8,
        quantity: 1,
        options: ['唐辛子なし'],
        memo: '辛味なし',
      },
      {
        id: 'fried-t33',
        tableNo: 'T33',
        elapsed: 7,
        quantity: 2,
        options: [],
        memo: '大皿まとめ',
      },
      {
        id: 'fried-t9',
        tableNo: 'T9',
        elapsed: 7,
        quantity: 1,
        options: [],
        memo: '大きめ',
      },
      {
        id: 'fried-t31',
        tableNo: 'T31',
        elapsed: 6,
        quantity: 1,
        options: ['ソース別皿'],
        memo: 'テーブル奥へ',
      },
      {
        id: 'fried-t5',
        tableNo: 'T5',
        elapsed: 6,
        quantity: 3,
        options: [],
        memo: '',
      },
      {
        id: 'fried-t27',
        tableNo: 'T27',
        elapsed: 5,
        quantity: 2,
        options: ['カット小さめ'],
        memo: '子ども用',
      },
      {
        id: 'fried-t52',
        tableNo: 'T52',
        elapsed: 4,
        quantity: 2,
        options: [],
        memo: '半分にカット',
      },
      {
        id: 'fried-t12',
        tableNo: 'T12',
        elapsed: 4,
        quantity: 1,
        options: [],
        memo: '',
        uiStatus: 'undoable',
        undoStartedAgoMs: 300,
      },
      {
        id: 'fried-t48',
        tableNo: 'T48',
        elapsed: 3,
        quantity: 1,
        options: ['衣うすめ'],
        memo: '塩なし',
      },
      {
        id: 'fried-t8',
        tableNo: 'T8',
        elapsed: 3,
        quantity: 2,
        options: [],
        memo: '焼き色強め',
      },
      {
        id: 'fried-t45',
        tableNo: 'T45',
        elapsed: 2,
        quantity: 2,
        options: ['レモン別添え', 'ソース別皿'],
        memo: '急ぎ',
      },
      {
        id: 'fried-t21',
        tableNo: 'T21',
        elapsed: 2,
        quantity: 1,
        options: ['+レモン別添え', 'カット小さめ', '衣うすめ', '先出し希望'],
        memo: '子ども用なので辛味なし',
      },
      {
        id: 'fried-t56',
        tableNo: 'T56',
        elapsed: 1,
        quantity: 1,
        options: ['取り皿追加'],
        memo: '一番最後で',
      },
    ],
  }),
  ...createOrderItemRows({
    categoryId: 'griddle',
    menuId: 'gyoza',
    name: '餃子',
    rows: [
      {
        id: 'gyoza-t4',
        tableNo: 'T4',
        elapsed: 10,
        quantity: 1,
        options: [],
        memo: '',
      },
      {
        id: 'gyoza-t18',
        tableNo: 'T18',
        elapsed: 5,
        quantity: 2,
        options: [],
        memo: '焼き強め',
      },
      {
        id: 'gyoza-t2',
        tableNo: 'T2',
        elapsed: 3,
        quantity: 4,
        options: [],
        memo: '',
        uiStatus: 'undoable',
        undoStartedAgoMs: 900,
      },
    ],
  }),
  ...createOrderItemRows({
    categoryId: 'salad',
    menuId: 'caesar',
    name: 'シーザーサラダ',
    rows: [
      {
        id: 'salad-t11',
        tableNo: 'T11',
        elapsed: 8,
        quantity: 1,
        options: ['ドレッシング別添え', 'クルトン抜き', 'チーズ多め'],
        memo: '',
      },
      {
        id: 'salad-t14',
        tableNo: 'T14',
        elapsed: 1,
        quantity: 1,
        options: ['取り分け用'],
        memo: 'ナッツアレルギー確認あり',
      },
    ],
  }),
  ...createOrderItemRows({
    categoryId: 'drink',
    menuId: 'highball',
    name: '角ハイボール',
    rows: [
      {
        id: 'drink-t6',
        tableNo: 'T6',
        elapsed: 5,
        quantity: 2,
        options: ['氷少なめ'],
        memo: '',
      },
      {
        id: 'drink-t17',
        tableNo: 'T17',
        elapsed: 1,
        quantity: 2,
        options: [],
        memo: '',
      },
    ],
  }),
];

function createOrderItemRows({ categoryId, menuId, name, rows }) {
  return rows.map((row, index) => ({
    id: row.id,
    order_item_id: `${row.id}-item`,
    order_id: `${row.id}-order`,
    category_id: categoryId,
    menu_id: menuId,
    name,
    memo: row.memo,
    custom_content_name: null,
    quantity: row.quantity,
    previous_quantity: null,
    menu_type: 'normal',
    course_name: null,
    toppings: createToppings(row.id, row.options),
    tables: [createTable(row.tableNo)],
    is_table_changed: false,
    manual_add: false,
    cooked_once: false,
    status: 'ordered',
    chef_status: 'uncooked',
    ordered_date: null,
    created_at: null,
    updated_at: null,
    mock_elapsed_minutes: row.elapsed,
    mock_created_sequence: index + 1,
    mock_ui_status: row.uiStatus ?? 'normal',
    mock_undo_started_ago_ms: row.undoStartedAgoMs,
  }));
}

function createToppings(orderItemId, options) {
  return options.map((option, index) => ({
    id: `${orderItemId}-topping-${index + 1}`,
    name: option,
    quantity: 1,
  }));
}

function createTable(tableNo) {
  return {
    table_use_id: `${tableNo.toLowerCase()}-use`,
    table_id: tableNo.replace(/^T/, ''),
    name: tableNo,
    status: 'started',
  };
}
